TA_SBF_PTI/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),    #YEEEEEEEEEEEEEEEE NGEBUG BERJAM-JAM AKHIRNYA BISA HAAAAAAAAAAAAAAAAAAAAAAAA T-T
    path('friends/', include(('friends.urls', 'friends_details'), namespace='friends_details')),    #YEEEEEEEEEEEEEEEE NGEBUG BERJAM-JAM AKHIRNYA BISA HAAAAAAAAAAAAAAAAAAAAAAAA T-T (2)
    path('', views.portfolio),
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

friends/urls.py
from django.urls import path
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friends, name="list"),
    path('create/', views.friends_create, name='create'),
    path('<slug>/', views.friends_details, name="details"),
    path('<slug>/comment/', views.add_comment, name="comment"),
]

accounts/models.py
from django.db import models

# Create your models here.

friends/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Friends(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    tempat_tanggal_lahir = models.CharField(default='', max_length=500)
    description = models.TextField(default='')
    line = models.CharField(default='', max_length=100)

    def __str__(self):
        return self.name

    def snippet(self):
        if len(self.description) > 20:
            return self.description[:20] + "..."
        else:
            return self.description

    class Meta:
        verbose_name_plural = "friends"

class Comment(models.Model):
    friend = models.ForeignKey(Friends, default='', on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    username = models.ForeignKey(User, default=None, on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField(default=None)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

friends/forms.py
from django import forms
from . import models


class CreateFriends(forms.ModelForm):
    class Meta:
        model = models.Friends
        fields = ['name', 'slug', 'tempat_tanggal_lahir', 'description', 'line']

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = [
            "text",
        ]

TA_SBF_PTI/views.py
from django.http import HttpResponse
from django.shortcuts import render


def portfolio(request):
    # return HttpResponse('Portfolio')
    return render(request, 'portfolio.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

friends/views.py
from django.shortcuts import render, redirect
from .models import Friends,Comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def friends(request):
    friends = Friends.objects.all().order_by('name')
    return render(request, 'friends/friends.html', {'friends': friends})

def friends_details(request, slug):
    #return HttpResponse(slug)
    details = Friends.objects.get(slug=slug)
    comments = Comment.objects.filter(friend=details).order_by('created')
    number_comments = str(Comment.objects.filter(friend=details).count())
    return render(request, 'friends/friends_details.html', {'details': details,'comments':comments, 'number_comments': number_comments})


@login_required(login_url='/accounts/login/')
def friends_create(request):
    if request.method == "POST":
        form = forms.CreateFriends(request.POST, request.FILES)
        if form.is_valid():
            # save friend to db
            instance = form.save(commit=False)
            instance.username = request.user
            instance.save()
            return redirect('friends:list')
    else:
        form = forms.CreateFriends()
    return render(request, 'friends/friends_create.html', {'form':form})

@login_required(login_url="/accounts/login")
def add_comment(request, slug):
    friend = Friends.objects.get(slug=slug)
    if request.method == "POST":
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.username = request.user
            instance.friend = friend
            instance.save()
            return redirect('friends:details', slug=slug)
    else:
        form = forms.CreateComment()
    return render(request, 'friends/comment_create.html', {'form': form, 'friend':friend})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="site-form">Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="site-form">Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

friends/templates/friends/comment_create.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="create-comment">
        <h2>Write Your Comment Here!</h2>
        <form class="site-form" action="{% url 'friends:comment' slug=friend.slug %}" method="POST">
            {% csrf_token %}
            {{ form.text }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

friends/templates/friends/friends.html
{% extends 'base_layout.html' %}


{% block content %}
    <h1 class="friends"> Friends List </h1>
    <div class="friends">
        {% for friend in friends %}
            <div class='friend'>
                <h2><a href="{% url 'friends_details:details' slug=friend.slug %}"> {{ friend.name }} </a></h2>
                <p>Description: {{ friend.snippet }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

friends/templates/friends/friends_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-friends">
        <h2>Add a new friend</h2>
        <form class="site-form" action="{% url 'friends:create' %}" method="post">
            {% csrf_token %}
            <ul class="contactList">
                <li>Name: {{ form.name }}</li>
                <li>Slug: {{ form.slug }}</li>
                <li>Place and Date of Birth: {{ form.tempat_tanggal_lahir }}</li>
                <li class= "desc">Description: <br><br>{{ form.description }}</li>
                <li>Line ID: {{ form.line }}</li>
            </ul>
            <input type="submit" value="Create">
        </form>
    </div>

{% endblock %}

friends/templates/friends/friends_details.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="friends-details">
    <div class="details">
        <h2>Name: {{ details.name }}</h2>
        <p>Place and Date of Birth: {{ details.tempat_tanggal_lahir }}</p>
        <p>Description: {{ details.description }}</p>
        <p>Line ID: {{ details.line }}</p>
        <br>
        <hr>
        <br>
        <h2 class="commenttitle">Comments:</h2>
        <a class="button" href="{% url 'friends:comment' slug=details.slug %}">Add a Comment</a>
        <br>
        <h3 class="count">Total Comments: {{ number_comments }} </h3>
        {% for comment in comments %}
            <div class="comment">
                <strong class="username">{{ comment.username }}</strong>
                <p class="commenttext">{{ comment.text }}</p>
                <p class="time">{{ comment.created }}</p>
            </div>
        {% empty %}
            <p>No comments here yet :(</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Friends</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h1 class="title">FRIENDS :)<br><br><a href="{% url 'friends:list' %}"><img src="{% static 'friends.jpg' %}"/></a></h1>
            <div class="nav-style">
                <nav>
                    <ul>
                        <li><a href="https://kefas-profile.herokuapp.com">My Profile</a></li>
                        <li><a href="https://kefas-profile.herokuapp.com/friends/">Friends</a></li>
                        {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'friends:create' %}" class="highlight">Add Friend</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            {% block content %}
            {% endblock %}
        </div>

    </body>
</html>

templates/portfolio.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Cephas Knight</title>
        <link href="{% static 'portfolio/Main.css' %}" rel="stylesheet">

    </head>

    <body>
        <!-- header start -->
        <div id="header" class="section">
            <p>Kefas Satrio Bangkit Solideantyo</p>
            <img alt="Cool shit" class="img-circle" src="{% static 'portfolio/images/kefas.jpg' %}" style="height:20%;width:20%;margin-top:60px;margin-bottom:85px">
        </div>
        <!-- header end -->
        <div class="nav-style">
            <nav>
                <ul>
                    <li><a href="https://kefas-profile.herokuapp.com">Kefas' Profile</a></li>
                    <li><a href="https://kefas-profile.herokuapp.com/friends/">Friends</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'friends:create' %}" class="highlight">Add Friend</a></li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>

        <!-- About Me section start -->
        <div class="section">
            <h1><span>About Me</span></h1>
            <p>
                Hey! I'm <strong>Kefas</strong>. I've never really learned HTML, CSS, and Django properly since I've been too busy studying DDP1 and Discrete Mathematics. This is my first time coding with HTML, CSS, and Django (actually coding in general since I have no coding experience at all in highschool). By <i>coding</i> I mean <i>copy-pasting</i> <b>"some"</b> codes from <a href="http://www.sololearn.com" class="sololearn"><ins>SoloLearn</ins></a>/<a href="https://stackoverflow.com/" class="sololearn"><ins>Stack Overflow</ins></a> and then modify them to get what I want.
                <br>
                So....
                <br>
                Yeah...
                <br>
                I don't really fully remember what <strong>ALL</strong> of these codes do (mostly the CSS and Django codes), but I do understand <i>some</i> parts of them.
                <br>
                Like, all I did was try to imagine what I want this website to look like, then I start looking for ways on how to do so from the internet because I am a legit beginner. <i>Even though I copy-pasted some codes from the internet</i>, at least I get to learn something from doing so.
                I learned a lot too from debugging the crap out of my codes, especially when I started coding with Django. Even now, I still don't expect myself to remember everything about how to code with Django in such a short amount of time since this is the first time I had my hands on Django.
                <br>
                I really hope I can be a member of the BEM PTI team soon so I can have more experience and improve my skills using HTML, CSS, and Django (and then actually manage to remember what all these codes are for).
                <br>
                OH... and I owe A LOT of thanks to Kak Jojo (my SBF PTI Teacher) for being patient with me (I kept asking him thousands of questions for days and kept him up till 3 A.M. just to answer me lmao) and I also want to thank <a href="https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg" class="netninja">The Net Ninja</a> for making easy-to-understand Django tutorials.
                <br>
                Because of these two people I managed to learn a lot about Django and able to make this website.
                <br>
                It's far from perfect,
                <br>
                but I am actually quite proud of it and I believe I can improve my skills soon. :)
            </p>
            <p class="quote">"I love anime" - Elon Musk</p>
        </div>
        <!-- About Me section end -->

        <div class="section">
            <h1><span>My CV</span></h1>
            <p class="cv"><img src="{% static 'portfolio/images/MY CV.png' %}" style="width:75%;height:75%;"></p>
        </div>


        <!-- My Achievements section start -->
        <div class="section">
            <h1><span>My Achievements</span></h1>
            <ul>
                <li><b><i>Cooked a 3-minute instant cup noodles in under 2 minutes</i></b></li>
                <p class="popmie"><img src ="http://assets.klikindomaret.com/products/10000975/10000975_1.jpg" style="width:30%;heigt:30%;"></p>
                <li><b><i>Beauty Make Up contest (1st place winner)</i></b></li>
                <p class="makeup"><img src="{% static 'portfolio/images/before after.jpg' %}" style="width:80%;height:80%;"></p>
                <li><b><i>Saved Bekasi from Godzilla</i></b></li>
                <p class="godzilla"><img src="{% static 'portfolio/images/zilla vs epas.jpg' %}" style="width:80%;height:80%;"></p>
                <li><b><i>Menemukan cara mandi air hangat di tempat kost menggunakan ricecooker</i></b></li>
                <p class="godzilla"><img src="{% static 'portfolio/images/mandi ricecooker.jpg' %}" style="width:50%;height:50%;"></p>


            </ul>


        </div>
        <!-- My Schedule section end -->


        <!-- My Skills section start -->
        <div class="section">
            <h1><span>My Skills</span></h1>
            <ul>
                </li>
                <li>Microsoft Office <br>
                    <progress min="0" max="100" value="75"></progress>
                </li>
                <li>Photoshop <br />
                    <progress min = "0" max="100" value="55"></progress>
                </li>
                <li>Python <br />
                    <progress min="0" max="100" value="40"></progress>
                </li>
                <li>HTML, CSS, Django <br />
                    <progress min="0" max="100" value="20"></progress>
                </li>

            </ul>
        </div>
        <!-- My Skills section end -->
        <!-- FAQ -->
        <div class="section">
            <h1><span>F.A.Q</span></h1>
            <ul>
                <li>Kefas, Kefas apa yang bikin adem?<br>
                     <img src="https://www.static-src.com/wcsstore/Indraprastha/images/catalog/medium//93/MTA-1643457/cosmos_cosmos-16sdb-stand-fan--16-inch-_full02.jpg" style="height:50%; width:50%;">
                    <p><i>Kefas angin</i></p>
                </li>
                <br>
                <li>Kefas, Kefas apa yang lembut?<br>
                    <img src= "https://img.okeinfo.net/content/2015/04/13/194/1133181/intip-manfaat-bola-kapas-bagi-kecantikan-yIPtVeEtHS.jpg" style="height: 50%; width: 50%;">
                    <p><i>Kepas</i></p>
                </li>
                <li>Apa yang terjadi bila Kefas ditaruh di ruangan bersuhu tinggi?<br>
                    <img src="https://asset.kompas.com/crop/2x3:998x667/750x500/data/photo/2017/07/05/1117909854.jpg" style="height: 50%; width: 50%;">
                    <p><i>Kefanasan</i></p>
                </li>
                <li>Kemanakah Kefas pergi jika ingin berbelanja?<br>
                    <img src="https://img.beritasatu.com/cache/beritasatu/910x580-2/141465633732.jpg" style="height: 50%; width: 50%;">
                    <p><i>Kefasar</i></p>
                </li>
            </ul>
        </div>

         <!-- Media section start -->
        <div class="section">
            <h1><span>Brand Recommendations</span></h1>
            <h4 align="center"> Nutrisari </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/c1HhkGcC0OA" allowfullscreen></iframe>
            <h4 align="center"> Mecin </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/At2_qCUZrCw" allowfullscreen></iframe>
            <h4 align="center"> Tolak Angin </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/PEO7nq20VZw" allowfullscreen></iframe>


        </div>
        <!-- Media section end -->


        <!-- Contacts section start -->
        <div class="section" id="contacts">
            <h1><span>Follow Me!</span></h1>
            <div>
                <a href="https://www.facebook.com/profile.php?id=100010642963869" target="_blank">
                    <img style="height:5%; width:5%;" alt="Facebook" src="https://en.facebookbrand.com/wp-content/uploads/2016/05/flogo_rgb_hex-brc-site-250.png" />
                </a>
                <a href="https://www.instagram.com/kefas_satrio/?hl=en" target = "_blank">
                    <p class="ig"><img style="height:7%; width:7%;" alt="Instagram" src="https://www.brandchannel.com/wp-content/uploads/2016/05/instagram-new-logo-may-2016.jpg"/></p>
                </a>
                <a href="https://twitter.com/kefas_satrio" target = "_blank">
                    <img style="height:6%; width:6%;" alt="Twitter" src="https://www.sololearn.com/Uploads/icons/twitter.png" />
                </a>
            </div>
        </div>
        <!-- Contacts section end -->

        <div class="section" >
            <p align="center"><img style="height:70%; width:70%;" alt="Thank You" src="{% static 'portfolio/images/thank you.jpg' %}" /></p>
        </div>

    </body>
</html>